### ISSUE TITLE
\ Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

### ISSUE THREAD

**Issue by suriya-rgb** [apigee/apigeetool-node#190] opened 2020-05-28 08:21 UTC
\ Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! Unexpected end of JSON input while parsing near '...e-map":"^0.5.7","spri'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nishant\AppData\Roaming\npm-cache\_logs\2020-05-28T05_24_12_995Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

I have been getting this error while creating new app of angular. How to resolve this issues?

_Originally posted by @surajacharya62 in https://github.com/apigee/apigeetool-node/issues/184#issuecomment-635110840_

**Comment by krishna9325** [comment] 2020-05-31 20:15
This is my error, help me 

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> core-js@3.6.4 postinstall C:\Users\Krishna\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Krishna\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.3.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Krishna\package.json'
npm WARN @angular-devkit/build-angular@0.901.7 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN @ngtools/webpack@9.1.7 requires a peer of @angular/compiler-cli@>=9.0.0 < 10 but none is installed. You must install peer dependencies yourself.
npm WARN Krishna No description
npm WARN Krishna No repository field.
npm WARN Krishna No README data
npm WARN Krishna No license field.

**Comment by prajapatarun** [comment] 2020-06-04 18:29
same issue

**Comment by HK-Dilip-kumar** [comment] 2020-06-06 17:13
same issue

**Comment by rockyyap** [comment] 2020-06-08 10:02
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN @zowe/db2-for-zowe-cli@4.0.6 requires a peer of @zowe/imperative@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @zowe/db2-for-zowe-cli@4.0.6 requires a peer of @zowe/cli@^6.0.0 but none is installed. You must install peer dependencies yourself.

I got this message too. Maybe need to install separately.

**Comment by whitlockjc** [comment] 2020-06-08 23:09
Duplicate of #184

**Closed by whitlockjc** 2020-06-08 23:09 UTC

**Comment by taherkhans** [comment] 2020-08-12 12:32
Here is the solution:

Open your command prompt  and uninstall angular/cli by using 
"npm uninstall -g angular-cli" command.

Remove node_modules directory and then clear the cache by using 
"npm cache clear --force" command.

Remove 
C:\Users\<username>\AppData\Roaming\npm\ 
you can remove the folder this way 
rmdir C:\Users\<username>\AppData\Roaming\npm\  /s
and
 C:\Users\<username>\AppData\Roaming\npm-cache.
you can remove the folder this way 
rmdir C:\Users\<username>\AppData\Roaming\npm-cache  /s 

Now try to install the angular/cli@latest by using npm install -g @angular/cli@latest command.

**Comment by rahulraj871** [comment] 2020-08-15 14:22
this worked thanks !!

**Comment by Jigar-Kakadiya** [comment] 2020-08-17 12:57
it's working.
thanks

**Comment by Sudhansusuvam** [comment] 2020-08-17 17:36
its working ....!!!

**Comment by KhadijaWilliams** [comment] 2020-08-18 05:49
Does this work on a mac as well?

**Comment by taherkhans** [comment] 2020-08-18 14:25
> Does this work on a mac as well?

if you are working on mac , please try this and let every one know, thanks

**Comment by oviii123** [comment] 2020-08-24 15:00
Thankyou very much man....it s working...
