### ISSUE TITLE
When running deployproxy with -i (just upload a new revision, don't deploy it), it works, but throws an error

### ISSUE THREAD

**Issue by btallman** [apigee/apigeetool-node#19] opened 2015-08-14 19:11 UTC
When running deployproxy with -i (just upload a new revision, don't deploy it), it works, but throws an error (shown below). It seems to be still attempting to parse the deployment message, even though there isn't one.
+++++++++++++++++++++++++++++

Not deploying the proxy right now

TypeError: Cannot read property 'aPIProxy' of undefined
    at Object.module.exports.parseDeploymentResult (/usr/local/lib/node_modules/apigeetool/lib/commands/parsedeployments.js:42:9)
    at /usr/local/lib/node_modules/apigeetool/lib/commands/deployproxy.js:116:43
    at /usr/local/lib/node_modules/apigeetool/node_modules/async/lib/async.js:254:17
    at /usr/local/lib/node_modules/apigeetool/node_modules/async/lib/async.js:157:25
    at /usr/local/lib/node_modules/apigeetool/node_modules/async/lib/async.js:251:21
    at /usr/local/lib/node_modules/apigeetool/node_modules/async/lib/async.js:615:34
    at deployProxy (/usr/local/lib/node_modules/apigeetool/lib/commands/deployproxy.js:576:5)
    at async.series.deployResult (/usr/local/lib/node_modules/apigeetool/lib/commands/deployproxy.js:104:7)
    at /usr/local/lib/node_modules/apigeetool/node_modules/async/lib/async.js:610:21
    at /usr/local/lib/node_modules/apigeetool/node_modules/async/lib/async.js:249:17

**Comment by theganyo** [comment] 2015-09-17 18:34
Duplicate of #4

**Closed** 2015-09-17 18:34 UTC
