### ISSUE TITLE
Dont understand this

### ISSUE THREAD

**Issue by solomonugo** [apigee/apigeetool-node#191] opened 2020-06-04 10:59 UTC
Installing packages...npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see palantir/tslint#4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see request/request#3142
npm ERR! code EINTEGRITY
npm ERR! sha512-kjFgaTB2ckr9lgmkS1dOGRT7kmzpQueydxsxXSHWgICNVE6F/u1PHyeSOyJRpxW0GnrkLq3QM2EUFnQGGga5bg== integrity checksum failed when using sha512: wanted sha512-kjFgaTB2ckr9lgmkS1dOGRT7kmzpQueydxsxXSHWgICNVE6F/u1PHyeSOyJRpxW0GnrkLq3QM2EUFnQGGga5bg== but got sha512-X9OOVz2jaDw33o3jYVH05Gf5Gv6Iho1r/XBu1Ce2/yRahvEbP8olcsNkO2OKhN6VH19EZHts3ipwQYdQThqwIQ==. (163103 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Solomon Azowenu\AppData\Roaming\npm-cache_logs\2020-06-04T10_43_38_551Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

Please how do i resolve it....Or should i continue with the project like that

**Comment by solomonugo** [comment] 2020-06-04 11:26
Its working now....i had to uninstall nodejs and re install it again then updated it and its working fine...for now lol

**Comment by whitlockjc** [comment] 2020-06-08 23:09
Duplicate of #184

**Closed by whitlockjc** 2020-06-08 23:09 UTC
