### ISSUE TITLE
Error while creating angular new project

### ISSUE THREAD

**Issue by rohanrao1** [apigee/apigeetool-node#194] opened 2020-08-10 10:47 UTC
Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! Unexpected end of JSON input while parsing near '...10"},"dist":{"integri'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\91999\AppData\Roaming\npm-cache\_logs\2020-08-10T10_43_27_344Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

what should i do?

**Comment by whitlockjc** [comment] 2020-08-10 16:05
This is a duplicate of #184, which has a lot of information on this.  TL;DR is that this error/warning you're running into has **NOTHING** to do with this project, and it is mentioned in #184.

**Closed by whitlockjc** 2020-08-10 16:05 UTC
