### ISSUE TITLE
Deployment fails when a keystore or target server is added in the service callout policy

### ISSUE THREAD

**Issue by anshul07** [apigee/apigeetool-node#70] opened 2017-04-25 23:18 UTC
Deployment through the node tool fails during the validation of the policy schema when a keystore or target server is added to the service callout policy. When I create a zip of the same proxy bundle and upload it to management UI then it deploys fine. 

Please find my keystore configuration in Service callout policy:

    <HTTPTargetConnection>
      <URL>https://myURL.com</URL>
      <SSLInfo>
          <Enabled>true</Enabled>
          <ClientAuthEnabled>true</ClientAuthEnabled>
          <KeyStore>openiam_tls_keystore</KeyStore>
          <KeyAlias>openiam_tls_client_cert</KeyAlias>
      </SSLInfo>
    </HTTPTargetConnection>

I tried to debug the issue and following is my understanding-

Apigee nodetool makes a post call to https://api.enterprise.apigee.com/v1/o/<org-name>/apis/<proxy-name>/revisions/<revision-no>/policies with policy content in body and in response Apigee is throwing back the error:

```
"{\n  \"code\" : \"beans.OtherValidationError\",\n  \"message\" : \"Unexpected Validation Error null\",\n  \"contexts\" : [ ]\n}"
 ```

**Comment by ssvaidyanathan** [comment] 2017-11-07 19:55
https://community.apigee.com/questions/49215/apigeetool-error-uploading-service-callout-policy.html

**Comment by Michael-McD** [comment] 2017-11-08 10:57
Is this being investigated?  I ask because I note that the original issue was raised way back in April and it still has not been resolved.

**Comment by noahdietz** [comment] 2017-11-08 16:34
Hi all, I am currently investigating it, thanks Sai for the bump

**Comment by noahdietz** [comment] 2017-11-08 17:23
I've found the root cause. It is an issue in the Apigee Management Server API, which means the issue cannot be completely fixed from Apigee tool. I will look into a work around for the time being while getting the fix pushed.

**Comment by Michael-McD** [comment] 2017-11-13 11:47
Hi @noahdietz any news of either the underlying fix or temp fix being deployed?

**Comment by Michael-McD** [comment] 2017-11-13 14:21
In the interim we're using the Apigee management API which does work:

**Comment by Michael-McD** [comment] 2017-11-30 17:25
Hi @noahdietz any news of an underlying fix being deployed?  We're trying to integrate our Apigee Proxies into our CI and have just discovered the same issue in attempting to deploy "Shared Flows" that reference a <LoadBalancer />.

**Comment by noahdietz** [comment] 2017-11-30 18:34
The fix will not be released until beginning of Jan 2018. I know this is a while away, and I apologize for the inconvenience. I believe using the aforementioned bundle import API is the available workaround.

To be clear, does the issue you just mentioned WRT deploying Shared Flows + LBs occur on `import` or `deployment` of the Shared Flow? If it is the former, `import`, then the fix inflight should resolve that issue as well.

Again, sorry for the inconvenience.

**Comment by Michael-McD** [comment] 2017-12-02 22:09
Hi @noahdietz, Thanx for the update.  To answer your question: Shared Flow fails on import.

**Comment by anshul07** [comment] 2018-03-26 00:51
@noahdietz any news on the fix ?

**Comment by dhayal1986** [comment] 2018-06-02 06:27
Has this issue been fixed?

**Comment by noahdietz** [comment] 2018-06-04 16:23
The fix for this was released. I will close this issue. If the issue persists, please reopen and paste any additional error messages. Thank you for following up!

**Closed** 2018-06-04 16:23 UTC
